#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/17040692/clone ensure=absent force=true
puppet resource file /tmp/17040692/clone ensure=directory
cd /tmp/17040692/clone
git clone https://<your token>@github.com/<your repo>/devops_repo.git
cp -p /tmp/clone/devops_repo/index.html /var/www/html
