#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/17040692/clone ensure=absent force=true
puppet resource file /tmp/17040692/clone ensure=directory
cd /tmp/17040692/clone
git clone https://github.com/AdricLim/17040692_repo.git
cp -p /tmp/17040692/clone/17040692_repo/17040692_index.html /var/www/html/index.html 
